version: '3.8'

services:
  # Milvus Lite (简化版) - 本地模式
  milvus-lite:
    container_name: milvus-lite
    image: milvusdb/milvus-lite:latest
    ports:
      - "19530:19530"
    volumes:
      - ./volumes/milvus_lite:/var/lib/milvus
    environment:
      - MILVUS_LITE_DATA_PATH=/var/lib/milvus
    networks:
      - dev-network

  # Ollama 服务
  ollama:
    container_name: ollama-dev
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - dev-network
    restart: unless-stopped

  # 视角知识库应用（开发模式 - 本地模式）
  perspective-kb-dev-local:
    container_name: perspective-kb-dev-local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MILVUS_USE_SERVER=false
      - DB_PATH=milvus_lite.db
      - OLLAMA_HOST=http://ollama:11434
      - VECTOR_DIM=1024
      - BATCH_SIZE=50
      - MAX_WORKERS=2
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./src:/app/src  # 代码热重载
      - ./volumes/perspective_kb:/app/volumes
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - dev-network
    restart: unless-stopped
    command: >
      sh -c "
        echo '等待Ollama服务启动...' &&
        sleep 10 &&
        echo '拉取嵌入模型...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"mitoza/Qwen3-Embedding-0.6B:latest\"}' &&
        echo '启动开发服务器（本地模式）...' &&
        python -m src.main
      "

  # 视角知识库应用（开发模式 - 服务器模式）
  perspective-kb-dev-server:
    container_name: perspective-kb-dev-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MILVUS_USE_SERVER=true
      - MILVUS_HOST=milvus-lite
      - MILVUS_PORT=19530
      - OLLAMA_HOST=http://ollama:11434
      - VECTOR_DIM=1024
      - BATCH_SIZE=50
      - MAX_WORKERS=2
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./src:/app/src  # 代码热重载
      - ./volumes/perspective_kb:/app/volumes
    ports:
      - "8001:8000"
    depends_on:
      - milvus-lite
      - ollama
    networks:
      - dev-network
    restart: unless-stopped
    command: >
      sh -c "
        echo '等待Milvus Lite服务启动...' &&
        sleep 20 &&
        echo '等待Ollama服务启动...' &&
        sleep 10 &&
        echo '拉取嵌入模型...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"mitoza/Qwen3-Embedding-0.6B:latest\"}' &&
        echo '启动开发服务器（服务器模式）...' &&
        python -m src.main
      "

networks:
  dev-network:
    driver: bridge

volumes:
  milvus_lite:
  ollama:
  perspective_kb:
